# .github/workflows/build-zmk.yml

name: Build QMK Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_firmware:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build
      uses: qmk/qmk_action@v1
      with:
        keyboard: autokdk
        keymap: default
