jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: zmkfirmware/zmk-build-action@v2
        with:
          args: 'build'
          include:
            - board: akdk_bt1
              shield: split_ergo_tb_left
              snippet: studio-rpc-usb-uart
              cmake-args: -DCONFIG_ZMK_STUDIO=y
            - board: akdk_bt1
              shield: split_ergo_tb_right
              snippet: studio-rpc-usb-uart
              cmake-args: -DCONFIG_ZMK_STUDIO=y
            - board: akdk_bt1
              shield: settings_reset
